import sys
# Accounts data
# ACCOUNT FORMAT: [<username>, <password>, <money=200>, <is_admin=0>]
users = [["test", "1234"], ["wallace", "password"], ["admin", "terminator22", sys.maxsize, 1], ["a", "a", sys.maxsize, 1]]

# Events and artists data.
# EVENT FORMAT: [<ev_name>, <place>, <city>, <date>, <price>, <tickets_available>, [<artist>*N]
# ARTIST FORMAT: [<name>, <country>, <genre>]
events = [["Lovin Ibiza Festival", "Amnesia Ibiza", "Ibiza", "01-05-2020", "20", "1500",
         [["Marco Faraone", "Italy", "electronic"],
          ["Danny Serrano", "Spain", "trap"],
          ["Catz 'n Dogz", "Poland", "electronic"]]],
        ["Warm Up Festival 2020", "La fica", "Murcia", "01-10-2020", "42", "80000",[
            ["Leiva", "Spain", "pop"],
            ["Anni B Sweet", "Spain", "indie"],
            ["Kraftwek", "Germany", "electronic"],
            ["Hot Chip", "England", "electronic"],
            ["Jhonny Marr", "England", "indie"],
            ["Dorian", "Spain", "indie"],
            ["Carlos Sadness", "Spain", "indie"],
            ["Mando Diao", "Sweeden", "indie"],
            ["Viva Suecia", "Spain", "indie"],
            ["León Benavente", "Spain", "indie"],
            ["Rufus T.", "Spain", "rock"]]],
        ["Mallorca Live Festival 2020", "Calvià", "Mallorca", "08-10-2020", "82", "15000",[
            ["Michael Kiwanuka", "England", "trap"],
            ["Miles Kane", "England", "indie"],
            ["Kate Tempest", "England", "hip hop"],
            ["Carolina Durante", "Spain", "rock"],
            ["Delaossa", "Spain", "hip hop"],
            ["Nathy Peluso", "Argentina", "reggae"],
            ["Leiva", "Spain", "pop"],
            ["Crystal Fighters", "Spain", "indie"],
            ["Pet Shop Boys", "England", "electronic"],
            ["Miss Caffeina", "Spain", "indie"],
            ["Shinova", "Spain", "rock"],
            ["Monarchy", "England", "pop"]]],
        ["Festival Tomavistas 2020", "Parque Enrique Tierno Galván", "Madrid", "03-09-2020", "100", "10000", [
            ["Jarvis Cocker", "England", "pop"],
            ["Novedades Carminha", "Spain", "rock"],
            ["Allah-Las", "USA", "rock"],
            ["Cate Le Bon", "Wales", "indie"],
            ["Maika Makovski", "Spain", "pop"],
            ["León Benavente", "Spain", "indie"],
            ["El Columpio Asesino", "Spain", "rock"],
            ["Boy Pablo", "Norway", "indie"],
            ["Austra", "Canada", "electronic"],
            ["Mikal Cronin", "USA", "rock"], ["of Montreal", "USA", "rock"],
            ["Rolling Blackouts C.F", "Australia", "rock"],
            ["Axolotes Mexicanos", "Spain", "indie"],
            ["Dorian", "Spain", "indie"],
            ["The Horrors", "England", "rock"],
            ["Amaia", "Spain", "indie"],
            ["Anna Calvi", "England", "indie"],
            ["Nadia Rose", "England", "other"],
            ["Jessy Lanzan", "Canada", "electronic"],
            ["Bigott", "Spain", "indie"],
            ["Chloral", "Spain", "rock"]]],
        ["Primavera Sound 2020", "Oporto", "Portugal", "26-08-2020", "110", "10000", [
            ["Lana Del Rey", "USA", "pop"],
            ["Tyler, the Creator", "USA", "hip hop"],
            ["Yo La Tengo", "USA", "indie"],
            ["Chromatics", "USA", "electronic"],
            ["Pavement", "USA", "indie"],
            ["Mavis Staples", "USA", "rock"],
            ["Les Savy Fav", "USA", "rock"],
            ["Kim Gordon", "USA", "rock"],
            ["Paloma Mami", "Chile", "reggae"],
            ["Les Amazones d'Afrique", "Mali", "other"],
            ["Núria Graham", "Spain", "indie"],
            ["La Favi", "Spain", "reggae"],
            ["Die Katapult", "Spain", "electronic"],
            ["Lorena Álvarez", "Spain", "indie"]]],
        ["Madrid Puro Reggaeton Festival", "Ifema", "Madrid", "26-06-2020", "50", "7500", [
            ["Bad Bunny", "Puerto Rico", "reggae"],
            ["Daddy Yankee", "Puerto Rico", "reggae"],
            ["Maikel Delacalle", "Spain", "reggae"],
            ["Natti Natasha", "Republica Dominicana", "reggae"]]],
        ["Interestelar Sevilla 2020", "CAAC", "Sevilla", "04-09-2020", "60", "3500", [
            ["Leiva", "Spain", "pop"],
            ["Viva Suecia", "Spain", "indie"],
            ["Loquillo", "Spain", "rock"],
            ["Miss Caffeina", "Spain", "indie"],
            ["Guitarricadelafuente", "Spain", "other"],
            ["León Benavente", "Spain", "indie"],
            ["El Niño De La Hipoteca", "Spain", "rock"],
            ["Fuel Fandango", "Spain", "rock"],
            ["Lionware", "Spain", "other"]]],
        ["Granada Sound 2020", "Cortijo del Conde", "Granada", "18-09-2020", "38", "2000", [
            ["Dorian", "Spain", "indie"],
            ["Leiva", "Spain", "pop"],
            ["Amaral", "Spain", "rock"],
            ["Viva Suecia", "Spain", "indie"],
            ["Guitarricadelafuente", "Spain", "other"],
            ["Mando Diao", "Sweeden", "indie"]]],
        ["Festardor 2020", "Hornos Altos", "Valencia", "08-10-2020", "40", "3500", [
            ["La Polla Records", "Puerto Rico", "rock"]]],
        ["BBK Music Legends", "Goietxa Bidea", "Bilbao", "05-06-2021", "75", "5500", [
            ["Lucinda Williams", "USA", "rock"],
            ["The Jayhawks", "USA", "rock"],
            ["Eric Burdon", "England", "rock"],
            ["Maika Makovski", "Spain", "pop"],
            ["Anari", "Spain", "rock"],
            ["Joanna Connor", "USA", "other"],
            ["North Mississippi Allstars", "USA", "rock"]]],
        ["Bull Music Festival 2020", "Cortijo del Conde", "Granada", "09-10-2021", "30", "6500", [
            ["Natos y Waor", "Spain", "other"],
            ["El Kanka", "Spain", "trap"],
            ["Lola Indigo", "Spain", "pop"],
            ["Fernando Costa", "Spain", "hip hop"],
            ["Guitarricadelafuente", "Spain", "other"],
            ["Fyahbwoy", "Spain", "reggae"],
            ["Miguel Campello", "Spain", "reggae"],
            ["Second", "Spain", "indie"]]],
        ["Cranc Festival 2020", "Mahón", "Islas Baleares", "20-11-2021", "55", "8000", [
            ["Black Lips", "USA", "rock"],
            ["Holly Miranda", "USA", "pop"],
            ["Manel", "Spain", "indie"],
            ["Novedades Carminha", "Spain", "rock"],
            ["Maika Makovski", "Spain", "pop"],
            ["Califato ¾", "Spain", "electronic"],
            ["José Crepúsculo", "Spain", "indie"],
            ["Yana Zafiro", "Ukraine", "pop"]]]
        ]