"""empty message

Revision ID: 6759c0120bb5
Revises: 73ea0c4442a0
Create Date: 2020-04-30 12:32:16.977256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6759c0120bb5'
down_revision = '73ea0c4442a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    op.drop_table('events')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.Column('artist_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], )
    )
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('place', sa.VARCHAR(length=30), nullable=False),
    sa.Column('city', sa.VARCHAR(length=30), nullable=False),
    sa.Column('date', sa.VARCHAR(length=30), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('total_available_tickets', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'date', 'city')
    )
    op.create_table('artists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('country', sa.VARCHAR(length=30), nullable=False),
    sa.Column('genre', sa.VARCHAR(length=10), nullable=False),
    sa.CheckConstraint("genre IN ('REGGAE', 'POP', 'TRAP', 'HIP HOP', 'ROCK', 'INDIE', 'HEAVY', 'ELECTRONIC', 'OTHER')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
